import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from analyzer.models import Product

products = [
    # Moisturizers
    {"name": "HaYaH moisturizer 50ml", "category": "moisturizer", "skin_type": "oily", "description": "Provides deep hydration and reconstructive action to repair, soothe, and restore the natural moisture balance of oily and acne-prone skin.", "how_to_use": "Apply a small amount to clean, dry skin twice daily and massage gently until completely absorbed.", "image": "products image/HaYaH moisturizer_.jpg"},
    {"name": "Vacation Moisturizer 60ml", "category": "moisturizer", "skin_type": "dry", "description": "Provide deep hydration while brightening dark spots, improving skin elasticity with collagen, and offering high SPF protection against sun damage.", "how_to_use": "Apply a small amount to clean, dry skin twice daily and massage gently until fully absorbed.", "image": "products image/Vacation moisturizer_.jpg"},
    {"name": "Skykur moisturizer 120gm", "category": "moisturizer", "skin_type": "sensitive", "description": "Strengthens the skin barrier using Ceramides and Hyaluronic Acid while calming irritation and redness with Aloe Vera, Honey, and Zinc Oxide.", "how_to_use": "Apply a generous amount to the face or body, focusing on dry patches, twice daily.", "image": "products image/Skykur moisturizer_.jpg"},
    {"name": "Nano Treat 200ml", "category": "moisturizer", "skin_type": "dry", "description": "Delivers 72-hour deep hydration while strengthening the skin barrier with Ceramides and Hyaluronic Acid.", "how_to_use": "Apply a generous layer and massage gently onto a clean, damp face and neck twice daily.", "image": "products image/Nano Treat moisturizer_.jpg"},
    {"name": "MOIST-1", "category": "moisturizer", "skin_type": "combination", "description": "Delivers deep, long-lasting hydration through a rapidly absorbed, perfume-free formula that leaves no greasy residue.", "how_to_use": "Apply a generous amount to clean skin twice daily, gently massaging until completely absorbed.", "image": "products image/MOIST-1 moisturizer _.jpg"},
    {"name": "INFINITY 120ml", "category": "moisturizer", "skin_type": "all", "description": "Delivers deep, long-lasting hydration to restore moisture balance and soften the skin.", "how_to_use": "Smooth a generous layer over cleansed skin daily, massaging softly until completely absorbed.", "image": "products image/INFINITY moisturizer_.jpg"},
    {"name": "Dear 200gm", "category": "moisturizer", "skin_type": "all", "description": "Provides long-lasting, deep hydration while repairing the skin barrier using Panthenol, Ceramides, and Hyaluronic Acid.", "how_to_use": "Apply a rich layer to clean skin daily, massaging gently to lock in intense moisture.", "image": "products image/Dear moisturizer_.jpg"},
    {"name": "Cerave 236ml", "category": "moisturizer", "skin_type": "oily", "description": "Effectively removes excess oil and dirt without disrupting the protective skin barrier, utilizing 3 essential ceramides, niacinamide, and hyaluronic acid.", "how_to_use": "Wet skin with lukewarm water, massage into skin using gentle circular motions, and rinse thoroughly.", "image": "products image/Cerave moisturizer_.jpg"},
    {"name": "BIODERMA 40ml", "category": "moisturizer", "skin_type": "combination", "description": "Provides 48-hour ultra-moisturizing compensating care to soothe irritation and restore skin comfort.", "how_to_use": "Apply once or twice a day to gently cleansed skin, massaging lightly until fully absorbed.", "image": "products image/BIODERMA moisturizer_.jpg"},
    {"name": "VICHY 30ml", "category": "moisturizer", "skin_type": "all", "description": "Delivers long-lasting hydration while actively correcting breakouts, blackheads, and post-acne marks using 2% Salicylic Acid and Hyaluronic Acid.", "how_to_use": "Apply a light, even layer to a cleansed face morning and evening, avoiding the eye area.", "image": "products image/VIICHY moisturizer_.jpg"},

    # Cleansers
    {"name": "TEA TREE 150ml", "category": "cleanser", "skin_type": "oily", "description": "Deeply purifies pores and gently exfoliates using Tea Tree, Green Tea, and Lactic Acid to clear breakouts.", "how_to_use": "Pump foam onto built-in silicone brush, massage gently onto damp skin in circular motions, and rinse well.", "image": "products image/TEA TREE Facial Foam cleanser_.jpg"},
    {"name": "Neutrogena 200ml", "category": "cleanser", "skin_type": "all", "description": "Clinically proven to cleanse pores and remove dirt, oil, and impurities.", "how_to_use": "Wet face, pump cleanser into hands, massage face gently, and rinse thoroughly.", "image": "products image/Neutrogena cleanser_.jpg"},
    {"name": "LEYLAK 200ml", "category": "cleanser", "skin_type": "all", "description": "Purifies the skin, regulates sebum production, and removes makeup without causing irritation or dryness.", "how_to_use": "Apply to damp skin, gently massage to lather and remove impurities, then rinse thoroughly.", "image": "products image/LEYLAK cleanser_.jpg"},
    {"name": "Dermactive 250ml", "category": "cleanser", "skin_type": "oily", "description": "Gently cleanses, purifies, limits excess sebum production, and smooths the skin with a soap-free formula.", "how_to_use": "Lather onto damp skin, massage gently to cleanse, and rinse off easily with water.", "image": "products image/dermactive cleanser _.jpg"},
    {"name": "Beesline 200ml", "category": "cleanser", "skin_type": "all", "description": "Tones pores, calms, softens, and boosts radiance using a 97% natural blend of AHA, Pro-Vitamin B5, and calming rose water.", "how_to_use": "Apply to a cotton pad and gently sweep across a cleansed face and neck before applying serums or moisturizers.", "image": "products image/Beesline cleanser_.jpg"},
    {"name": "CLEO 125ml", "category": "cleanser", "skin_type": "all", "description": "Purifies, gently exfoliates, and illuminates the complexion with a paraben-free formula.", "how_to_use": "Massage onto damp skin to create a lather, then rinse thoroughly with water.", "image": "products image/CLEO cleanser_.jpg"},
    {"name": "BIODERMA 100ml", "category": "cleanser", "skin_type": "combination", "description": "Unclogs pores, cleanses deeply, and smooths skin texture using a purifying exfoliating gel formula.", "how_to_use": "Massage gently onto a damp face using circular motions for 1-2 minutes, then rinse thoroughly.", "image": "products image/BIODERMA cleanser_.jpg"},
    {"name": "Cerave 473ml", "category": "cleanser", "skin_type": "all", "description": "Cleanses and removes excess oil without disrupting the skin barrier using ceramides, niacinamide, and hyaluronic acid.", "how_to_use": "Wet skin, massage the cleanser into the face using gentle circular motions, and rinse thoroughly.", "image": "products image/Cerave Foaming Cleanser _.jpg"},
    {"name": "Appe Cleanser", "category": "cleanser", "skin_type": "oily", "description": "Purifies and nourishes the skin while regulating excess oil using a protein-rich formula.", "how_to_use": "Apply to a damp face, massage gently to cleanse, and rinse thoroughly with water.", "image": "products image/Appe cleanser_.jpg"},
    {"name": "VICHY 400ml", "category": "cleanser", "skin_type": "all", "description": "Deeply cleanses and intensely purifies the skin using a gentle plant-origin cleansing base.", "how_to_use": "Lather onto a damp face, massage gently to purify, and rinse off thoroughly with water.", "image": "products image/VICHY cleanser_.jpg"},

    # Serums
    {"name": "Ordinary 30ml", "category": "serum", "skin_type": "all", "description": "Exfoliates pores, clears blemishes, and improves skin texture.", "how_to_use": "Apply a small dot directly on spots or a small amount over the face PM.", "image": "products image/Ordinary serum_.jpg"},
    {"name": "LEYLAK Serum", "category": "serum", "skin_type": "all", "description": "Deeply hydrates the skin and brightens the complexion.", "how_to_use": "Apply a few drops to clean skin in the AM and PM before moisturizing.", "image": "products image/LEYLAK serum_.jpg"},
    {"name": "Starville 30ml", "category": "serum", "skin_type": "sensitive", "description": "Strengthens the skin barrier, repairs, and hydrates.", "how_to_use": "Apply 3-4 drops to a damp and cleansed face and neck AM and PM.", "image": "products image/Starville serum_.jpg"},
    {"name": "Glow mark 30ml", "category": "serum", "skin_type": "normal", "description": "Lightens dark spots, evens skin tone, and provides a healthy glow.", "how_to_use": "Apply 3-4 drops to a clean face and neck in the AM or PM before moisturizing.", "image": "products image/Glow mark serum _.jpg"},
    {"name": "GARNIER 30ml", "category": "serum", "skin_type": "all", "description": "Brightens skin tone, fades dark spots, and reduces acne marks in 3 days.", "how_to_use": "Apply a few drops on a clean face and neck, morning and night, before moisturizer.", "image": "products image/GARNIER serums_.jpg"},
    {"name": "EVA 30ml", "category": "serum", "skin_type": "all", "description": "Reduces fine lines, stimulates collagen, and evens out skin tone and texture.", "how_to_use": "Apply 2-4 drops at night on clean skin before moisturizer and use sunscreen the next day.", "image": "products image/EVA serum_.jpg"},
    {"name": "CLEO 30ml", "category": "serum", "skin_type": "all", "description": "Plumps skin to reduce fine lines while soothing inflammation and tightening pores.", "how_to_use": "Apply one pump twice daily, morning and evening, to a cleansed face and neck.", "image": "products image/CLEO serum_.jpg"},
    {"name": "Alejon 30ml", "category": "serum", "skin_type": "all", "description": "Reduces puffiness and dark circles while soothing the eye area.", "how_to_use": "Gently pat a small drop around the eye area morning and evening.", "image": "products image/Alejon serum _.jpg"},
    {"name": "Dermactive 30ml", "category": "serum", "skin_type": "combination", "description": "Eliminates spots and blackheads while minimizing pores and acne marks.", "how_to_use": "Apply 2-3 drops on dry, cleansed skin in the evening, avoiding the eyes.", "image": "products image/dermactive serum_.jpg"},
    {"name": "Cerave Serum 30ml", "category": "serum", "skin_type": "all", "description": "Provides 24-hour intense hydration, plumps the skin, and helps restore the protective barrier.", "how_to_use": "Apply evenly to a clean, slightly damp face and neck daily before moisturizing.", "image": "products image/Cerave serum_.jpg"},

    # Sunscreens
    {"name": "Beesline Sunscreen", "category": "sunscreen", "skin_type": "sensitive", "description": "Provides broad-spectrum UVA/UVB protection with a matte, invisible finish and no white cast.", "how_to_use": "Apply generously to face and neck 15 minutes before sun exposure and reapply every 2 hours.", "image": "products image/sunscreen Beesline_.jpg"},
    {"name": "Dermactive 50ml", "category": "sunscreen", "skin_type": "oily", "description": "Provides a mattifying, dry-touch finish that controls shine and absorbs quickly without leaving a white cast.", "how_to_use": "Apply evenly to the face and neck 15-20 minutes before sun exposure and reapply every 2 hours.", "image": "products image/dermactive sunscreen_.jpg"},
    {"name": "Vacation 60ml", "category": "sunscreen", "skin_type": "all", "description": "Provides deep hydration with collagen and Vitamin E while evening tone with licorice extract.", "how_to_use": "Apply generously 15-20 minutes before sun exposure and reapply every 2 hours.", "image": "products image/sunscreen vacation_.jpg"},
    {"name": "INFINITY 50ml", "category": "sunscreen", "skin_type": "oily", "description": "Controls excess oil for a 3-hour matte finish and protects against breakouts with Salicylic Acid.", "how_to_use": "Apply to the face and neck 15 minutes before sun exposure and reapply every 2 hours.", "image": "products image/INFINITY sunscreen_.jpg"},
    {"name": "HaYaH 50ml", "category": "sunscreen", "skin_type": "combination", "description": "Provides high sun protection with a matte finish and zero greasy residue.", "how_to_use": "Apply to the face and neck 20 minutes before sun exposure and reapply every 2 hours.", "image": "products image/HaYaH sunscreen_.jpg"},
    {"name": "LA Roch-Posay", "category": "sunscreen", "skin_type": "all", "description": "Provides ultra-high protection while evening out skin tone with a natural, tinted finish.", "how_to_use": "Shake the bottle well and apply to the face and neck 15 minutes before sun exposure.", "image": "products image/LA Roch-Posay sunscreen.jpg"},
    {"name": "BIODERMA 40ml Sunscreen", "category": "sunscreen", "skin_type": "sensitive", "description": "Provides ultra-light hydration with a dry-touch finish and high UV protection.", "how_to_use": "Apply evenly and generously to the face and neck daily before sun exposure.", "image": "products image/BIODERMA sunscreen_.jpg"},
    {"name": "Cerave Sunscreen", "category": "sunscreen", "skin_type": "all", "description": "Provides lightweight, mineral-based protection with an invisible finish that is water-resistant.", "how_to_use": "Apply liberally to the face or small areas 15 minutes before sun exposure and reapply every 2 hours.", "image": "products image/Cerave sunscreen_.jpg"},
    {"name": "Appe 60ml", "category": "sunscreen", "skin_type": "all", "description": "Provides high protection while evening out darker skin tones with a tinted finish and anti-aging benefits.", "how_to_use": "Apply a generous amount to the face and neck 15-20 minutes before sun exposure and reapply every 2 hours.", "image": "products image/Appe sunscreen_.jpg"},
    {"name": "VICHY 50ml", "category": "sunscreen", "skin_type": "combination", "description": "Provides high UV protection with a mattifying, anti-shine finish and a natural BB tint to even skin tone.", "how_to_use": "Apply to the face and neck 15-20 minutes before sun exposure and reapply every 2 hours.", "image": "products image/VICHY sunscreen_.jpg"},
]

for p in products:
    Product.objects.get_or_create(
        name=p['name'],
        defaults={
            'category': p['category'],
            'skin_type': p['skin_type'],
            'description': p['description'],
            'how_to_use': p['how_to_use'],
            'image': p['image'],
        }
    )
    print(f"✓ {p['name']}")

print("\nتم إضافة كل المنتجات بنجاح!")