# Generated by Django 6.0.3 on 2026-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('moisturizer', 'Moisturizer'), ('cleanser', 'Cleanser'), ('serum', 'Serum'), ('sunscreen', 'Sunscreen')], max_length=100)),
            ],
        ),
    ]
