# Generated by Django 6.0.3 on 2026-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('normal', 'Normal'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('all', 'All Skin Types')], default='oily', max_length=100),
            preserve_default=False,
        ),
    ]
